```{r}
# CARREGANDO OS PACOTE
library(pheatmap)
```

```{r}
#Importar e tratar dados
data <- read.csv("arquivo.csv", check.names = FALSE)
rnames <- data[,1]                            
mat_data <- data.matrix(data[,2:ncol(data)])
rownames(mat_data) <- rnames  
data=log2(mat_data)
data=log2(mat_data)
rownames(data) <- rnames
colnames(data) <- colnames(data)
```

```{r}
classe_dados <- data.frame("Classe" = c("Aminoglicosídeo","Aminoglicosídeo","Aminoglicosídeo","Aminoglicosídeo","Fosfomicina","Tetraciclina","	Sulfonamida","Sulfonamida","Beta-lactamase","Beta-lactamase","Trimetoprim","Fenicol"))
rownames(classe_dados) <- colnames(data)
mec_dados <- data.frame("Mecanismo" = c("Inativação do antimicrobiano","Inativação do antimicrobiano","Inativação do antimicrobiano","Inativação do antimicrobiano","Inativação do antimicrobiano","Bomba de efluxo","Modificação do alvo",	"Modificação do alvo","Inativação do antimicrobiano","Inativação do antimicrobiano",	"Substituição do alvo","Bomba de efluxo"))
rownames(mec_dados) <- colnames(data)

uniao_dataframe <- cbind(classe_dados,mec_dados)
```



```{r}
#Pheatmap
library(RColorBrewer)
pheatmap(
  #Matriz numerica 
  mat = data,
  # Vetor de cores usadas no mapa de calor
  color = colorRampPalette(brewer.pal(n=3,name = "Blues"))(100),
  #Numero de clusters kmeans a serem feitos
  kmeans_k = NA,
  # Cor das bordas da celula no mapa de calor 
  border_color = "black",
  #Largura e altura da celula 
  cellheight = NA,
  # Caractere que indica se os valores devem ser centralizados
  scale = "none",
  # Dendograma, cluster_rows e cluster_cols: valores booleanos que determinam
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  # Medida distancia usada em agrupamento das linhas ou colunas. 
  clustering_distance_rows = "euclidean",
  clustering_distance_cols = "euclidean",
  #Metodo de agrupamento usado
  clustering_method = "complete",
  #Legenda das cores
  legend = TRUE,
  # Vetor de pontos de interrupcao para a legenda
  legend_breaks = c(-1,6),
  legend_labels = c("Ausente","Presente"),
 #Quadro de dados que especifica as anotacoes mostradas 
  annotation_row = NA,
  annotation_col = uniao_dataframe,
  # Lista para especificar as cores 
  annotation_colors = NA,
  # Anotacao 
  annotation_legend = TRUE,
  annotation_names_row = TRUE,
  annotation_names_col = TRUE,
  # Determinar se os niveis nao uilizados tambem sao mostrados na legenda
  drop_levels = TRUE,
  #Nomes das linhas ou colunas sao mostrados
  show_rownames = TRUE,
  show_colnames = TRUE,
  # Titulo do grafico
  main = "ARG-ANNOT",
  #Formatação escrita
  fontsize = 16,
  fontsize_row = 16,
  fontsize_col = 16,
  # Angulo dos rotulos das colunas (0, 45, 90, 270 e 315)
  angle_col = "90",
  # Valores numericos tambem sao impressos nas celulas e formatação
  display_numbers = FALSE,
  number_format = "%.1f",
  number_color = "grey30",
  fontsize_number = 16,
  # Linhas ou colunas que sao usadas em vez de nomes de linha
  labels_row = NULL,
  labels_col = NULL,
  # salvar arquivo
  filename = "C:/Users/Desktop/heatmap.png",
  # Determinar a largura e altura do 
  width = 11,
  height = 8,
  # Especifica a cor da celula NA na matriz
  na_col = "#DDDDDD"
)



```
